/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as PortalRouteRouteImport } from './routes/_portal/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAccountingRouteImport } from './routes/_authenticated/accounting'
import { Route as AuthenticatedAssetsRouteImport } from './routes/_authenticated/assets'
import { Route as AuthenticatedCashRouteImport } from './routes/_authenticated/cash'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDashboard3plRouteImport } from './routes/_authenticated/dashboard-3pl'
import { Route as AuthenticatedDeclaracionesJuradasRouteImport } from './routes/_authenticated/declaraciones-juradas'
import { Route as AuthenticatedDispatchRouteImport } from './routes/_authenticated/dispatch'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedPosRouteImport } from './routes/_authenticated/pos'
import { Route as AuthenticatedProductionRouteImport } from './routes/_authenticated/production'
import { Route as AuthenticatedPurchasesRouteImport } from './routes/_authenticated/purchases'
import { Route as AuthenticatedSuppliersRouteImport } from './routes/_authenticated/suppliers'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedSalesRouteImport } from './routes/_authenticated/sales'
import { Route as AuthenticatedSetupRouteImport } from './routes/_authenticated/setup'
import { Route as AuthenticatedSiiBooksRouteImport } from './routes/_authenticated/sii-books'
import { Route as AuthenticatedTaxesRouteImport } from './routes/_authenticated/taxes'
import { Route as PortalPortalRouteImport } from './routes/_portal/portal'
import { Route as ApiWebhooksApipymeRouteImport } from './routes/api/webhooks/apipyme'
import { Route as ApiWebhooksOmsRouteImport } from './routes/api/webhooks/oms'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRouteRoute = PortalRouteRouteImport.update({
  id: '/_portal',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountingRoute = AuthenticatedAccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssetsRoute = AuthenticatedAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCashRoute = AuthenticatedCashRouteImport.update({
  id: '/cash',
  path: '/cash',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboard3plRoute =
  AuthenticatedDashboard3plRouteImport.update({
    id: '/dashboard-3pl',
    path: '/dashboard-3pl',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDeclaracionesJuradasRoute =
  AuthenticatedDeclaracionesJuradasRouteImport.update({
    id: '/declaraciones-juradas',
    path: '/declaraciones-juradas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDispatchRoute = AuthenticatedDispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPosRoute = AuthenticatedPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductionRoute = AuthenticatedProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPurchasesRoute = AuthenticatedPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSuppliersRoute = AuthenticatedSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSalesRoute = AuthenticatedSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSetupRoute = AuthenticatedSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSiiBooksRoute = AuthenticatedSiiBooksRouteImport.update({
  id: '/sii-books',
  path: '/sii-books',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTaxesRoute = AuthenticatedTaxesRouteImport.update({
  id: '/taxes',
  path: '/taxes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const PortalPortalRoute = PortalPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => PortalRouteRoute,
} as any)
const ApiWebhooksApipymeRoute = ApiWebhooksApipymeRouteImport.update({
  id: '/api/webhooks/apipyme',
  path: '/api/webhooks/apipyme',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksOmsRoute = ApiWebhooksOmsRouteImport.update({
  id: '/api/webhooks/oms',
  path: '/api/webhooks/oms',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/accounting': typeof AuthenticatedAccountingRoute
  '/assets': typeof AuthenticatedAssetsRoute
  '/cash': typeof AuthenticatedCashRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dashboard-3pl': typeof AuthenticatedDashboard3plRoute
  '/declaraciones-juradas': typeof AuthenticatedDeclaracionesJuradasRoute
  '/dispatch': typeof AuthenticatedDispatchRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/pos': typeof AuthenticatedPosRoute
  '/production': typeof AuthenticatedProductionRoute
  '/purchases': typeof AuthenticatedPurchasesRoute
  '/suppliers': typeof AuthenticatedSuppliersRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/setup': typeof AuthenticatedSetupRoute
  '/sii-books': typeof AuthenticatedSiiBooksRoute
  '/taxes': typeof AuthenticatedTaxesRoute
  '/portal': typeof PortalPortalRoute
  '/api/webhooks/apipyme': typeof ApiWebhooksApipymeRoute
  '/api/webhooks/oms': typeof ApiWebhooksOmsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/accounting': typeof AuthenticatedAccountingRoute
  '/assets': typeof AuthenticatedAssetsRoute
  '/cash': typeof AuthenticatedCashRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dashboard-3pl': typeof AuthenticatedDashboard3plRoute
  '/declaraciones-juradas': typeof AuthenticatedDeclaracionesJuradasRoute
  '/dispatch': typeof AuthenticatedDispatchRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/pos': typeof AuthenticatedPosRoute
  '/production': typeof AuthenticatedProductionRoute
  '/purchases': typeof AuthenticatedPurchasesRoute
  '/suppliers': typeof AuthenticatedSuppliersRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/setup': typeof AuthenticatedSetupRoute
  '/sii-books': typeof AuthenticatedSiiBooksRoute
  '/taxes': typeof AuthenticatedTaxesRoute
  '/portal': typeof PortalPortalRoute
  '/api/webhooks/apipyme': typeof ApiWebhooksApipymeRoute
  '/api/webhooks/oms': typeof ApiWebhooksOmsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_portal': typeof PortalRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/accounting': typeof AuthenticatedAccountingRoute
  '/_authenticated/assets': typeof AuthenticatedAssetsRoute
  '/_authenticated/cash': typeof AuthenticatedCashRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/dashboard-3pl': typeof AuthenticatedDashboard3plRoute
  '/_authenticated/declaraciones-juradas': typeof AuthenticatedDeclaracionesJuradasRoute
  '/_authenticated/dispatch': typeof AuthenticatedDispatchRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/pos': typeof AuthenticatedPosRoute
  '/_authenticated/production': typeof AuthenticatedProductionRoute
  '/_authenticated/purchases': typeof AuthenticatedPurchasesRoute
  '/_authenticated/suppliers': typeof AuthenticatedSuppliersRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/sales': typeof AuthenticatedSalesRoute
  '/_authenticated/setup': typeof AuthenticatedSetupRoute
  '/_authenticated/sii-books': typeof AuthenticatedSiiBooksRoute
  '/_authenticated/taxes': typeof AuthenticatedTaxesRoute
  '/_portal/portal': typeof PortalPortalRoute
  '/api/webhooks/apipyme': typeof ApiWebhooksApipymeRoute
  '/api/webhooks/oms': typeof ApiWebhooksOmsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/accounting'
    | '/assets'
    | '/cash'
    | '/dashboard'
    | '/dashboard-3pl'
    | '/declaraciones-juradas'
    | '/dispatch'
    | '/inventory'
    | '/pos'
    | '/production'
    | '/purchases'
    | '/suppliers'
    | '/reports'
    | '/sales'
    | '/setup'
    | '/sii-books'
    | '/taxes'
    | '/portal'
    | '/api/webhooks/apipyme'
    | '/api/webhooks/oms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/accounting'
    | '/assets'
    | '/cash'
    | '/dashboard'
    | '/dashboard-3pl'
    | '/declaraciones-juradas'
    | '/dispatch'
    | '/inventory'
    | '/pos'
    | '/production'
    | '/purchases'
    | '/suppliers'
    | '/reports'
    | '/sales'
    | '/setup'
    | '/sii-books'
    | '/taxes'
    | '/portal'
    | '/api/webhooks/apipyme'
    | '/api/webhooks/oms'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_portal'
    | '/auth'
    | '/_authenticated/accounting'
    | '/_authenticated/assets'
    | '/_authenticated/cash'
    | '/_authenticated/dashboard'
    | '/_authenticated/dashboard-3pl'
    | '/_authenticated/declaraciones-juradas'
    | '/_authenticated/dispatch'
    | '/_authenticated/inventory'
    | '/_authenticated/pos'
    | '/_authenticated/production'
    | '/_authenticated/purchases'
    | '/_authenticated/suppliers'
    | '/_authenticated/reports'
    | '/_authenticated/sales'
    | '/_authenticated/setup'
    | '/_authenticated/sii-books'
    | '/_authenticated/taxes'
    | '/_portal/portal'
    | '/api/webhooks/apipyme'
    | '/api/webhooks/oms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  PortalRouteRoute: typeof PortalRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiWebhooksApipymeRoute: typeof ApiWebhooksApipymeRoute
  ApiWebhooksOmsRoute: typeof ApiWebhooksOmsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_portal': {
      id: '/_portal'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PortalRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/accounting': {
      id: '/_authenticated/accounting'
      path: '/accounting'
      fullPath: '/accounting'
      preLoaderRoute: typeof AuthenticatedAccountingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assets': {
      id: '/_authenticated/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AuthenticatedAssetsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cash': {
      id: '/_authenticated/cash'
      path: '/cash'
      fullPath: '/cash'
      preLoaderRoute: typeof AuthenticatedCashRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard-3pl': {
      id: '/_authenticated/dashboard-3pl'
      path: '/dashboard-3pl'
      fullPath: '/dashboard-3pl'
      preLoaderRoute: typeof AuthenticatedDashboard3plRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/declaraciones-juradas': {
      id: '/_authenticated/declaraciones-juradas'
      path: '/declaraciones-juradas'
      fullPath: '/declaraciones-juradas'
      preLoaderRoute: typeof AuthenticatedDeclaracionesJuradasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dispatch': {
      id: '/_authenticated/dispatch'
      path: '/dispatch'
      fullPath: '/dispatch'
      preLoaderRoute: typeof AuthenticatedDispatchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pos': {
      id: '/_authenticated/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof AuthenticatedPosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/production': {
      id: '/_authenticated/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof AuthenticatedProductionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchases': {
      id: '/_authenticated/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof AuthenticatedPurchasesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/suppliers': {
      id: '/_authenticated/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AuthenticatedSuppliersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales': {
      id: '/_authenticated/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AuthenticatedSalesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/setup': {
      id: '/_authenticated/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof AuthenticatedSetupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sii-books': {
      id: '/_authenticated/sii-books'
      path: '/sii-books'
      fullPath: '/sii-books'
      preLoaderRoute: typeof AuthenticatedSiiBooksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/taxes': {
      id: '/_authenticated/taxes'
      path: '/taxes'
      fullPath: '/taxes'
      preLoaderRoute: typeof AuthenticatedTaxesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_portal/portal': {
      id: '/_portal/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalPortalRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/api/webhooks/apipyme': {
      id: '/api/webhooks/apipyme'
      path: '/api/webhooks/apipyme'
      fullPath: '/api/webhooks/apipyme'
      preLoaderRoute: typeof ApiWebhooksApipymeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/oms': {
      id: '/api/webhooks/oms'
      path: '/api/webhooks/oms'
      fullPath: '/api/webhooks/oms'
      preLoaderRoute: typeof ApiWebhooksOmsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountingRoute: typeof AuthenticatedAccountingRoute
  AuthenticatedAssetsRoute: typeof AuthenticatedAssetsRoute
  AuthenticatedCashRoute: typeof AuthenticatedCashRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDashboard3plRoute: typeof AuthenticatedDashboard3plRoute
  AuthenticatedDeclaracionesJuradasRoute: typeof AuthenticatedDeclaracionesJuradasRoute
  AuthenticatedDispatchRoute: typeof AuthenticatedDispatchRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedPosRoute: typeof AuthenticatedPosRoute
  AuthenticatedProductionRoute: typeof AuthenticatedProductionRoute
  AuthenticatedPurchasesRoute: typeof AuthenticatedPurchasesRoute
  AuthenticatedSuppliersRoute: typeof AuthenticatedSuppliersRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSalesRoute: typeof AuthenticatedSalesRoute
  AuthenticatedSetupRoute: typeof AuthenticatedSetupRoute
  AuthenticatedSiiBooksRoute: typeof AuthenticatedSiiBooksRoute
  AuthenticatedTaxesRoute: typeof AuthenticatedTaxesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountingRoute: AuthenticatedAccountingRoute,
  AuthenticatedAssetsRoute: AuthenticatedAssetsRoute,
  AuthenticatedCashRoute: AuthenticatedCashRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDashboard3plRoute: AuthenticatedDashboard3plRoute,
  AuthenticatedDeclaracionesJuradasRoute:
    AuthenticatedDeclaracionesJuradasRoute,
  AuthenticatedDispatchRoute: AuthenticatedDispatchRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedPosRoute: AuthenticatedPosRoute,
  AuthenticatedProductionRoute: AuthenticatedProductionRoute,
  AuthenticatedPurchasesRoute: AuthenticatedPurchasesRoute,
  AuthenticatedSuppliersRoute: AuthenticatedSuppliersRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSalesRoute: AuthenticatedSalesRoute,
  AuthenticatedSetupRoute: AuthenticatedSetupRoute,
  AuthenticatedSiiBooksRoute: AuthenticatedSiiBooksRoute,
  AuthenticatedTaxesRoute: AuthenticatedTaxesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface PortalRouteRouteChildren {
  PortalPortalRoute: typeof PortalPortalRoute
}

const PortalRouteRouteChildren: PortalRouteRouteChildren = {
  PortalPortalRoute: PortalPortalRoute,
}

const PortalRouteRouteWithChildren = PortalRouteRoute._addFileChildren(
  PortalRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  PortalRouteRoute: PortalRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiWebhooksApipymeRoute: ApiWebhooksApipymeRoute,
  ApiWebhooksOmsRoute: ApiWebhooksOmsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
